name: pra_tvi_web
description: Ruts gets Pranked!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  flutter_svg: ^1.1.5
  url_launcher: ^6.1.4
  shared_preferences: ^2.0.15
  page_transition: ^2.0.5
  resize: ^1.0.0
  connectivity_plus: ^3.0.2
  get: ^4.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_typeahead: ^4.1.1

  #INFO: firebase dependencies
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.2

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/pra_tvi_web_logo.png"
  adaptive_icon_background: "#F6F5E8"
  adaptive_icon_foreground: "assets/images/pra_tvi_web_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:

  uses-material-design: true
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat_300.ttf
          weight: 300
        - asset: assets/fonts/montserrat_400.ttf
          style: normal
        - asset: assets/fonts/montserrat_500.ttf
          weight: 500
        - asset: assets/fonts/montserrat_600.ttf
          weight: 600
        - asset: assets/fonts/montserrat_700.ttf
          weight: 700
    - family: script
      fonts:
        - asset: assets/fonts/script_500.ttf
          weight: 500
        - asset: assets/fonts/script_600.ttf
          weight: 600

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/